# Basic
title: Shan's hub
SEOTitle: sj2921@columbia.edu
header-img: img/home-bg.jpg
email: sj2921@columbia.edu
keyword: New Yorker, Blog writter, novelist, R, biostatistics, 
welcome_message: Now I am working on Energy insecuirity and applications of data visulization on social science topics, for more information, <a href="https://shanjiang21.github.io/sociology.html">click here</a>
description: Hi, I am Shan(@shanjiang21), a master student at Columbia University.
url: "https://shanj.tk/"
baseurl: ""

# Publish posts or collection documents with a future date.
future: true

# SNS settings
linkedin_username: shan-jiang-983639153
weibo_username: jason96026
github_username: shanjiang21

# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
highlighter: rouge
permalink: pretty
paginate: 12
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md","README.zh.md"]
anchorjs: true

# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "The sun always finds a way to shine its light on us<br>怀疑主义者其实都是有信仰的人……嘘，别嚷嚷。"
sidebar-avatar: /img/avatar.jpg

# Featured Tags
featured-tags: true                     # whether or not using Feature-Tags
featured-condition-size: 1.3              # A tag will be featured if the size of it is more than this condition value

# Gems
# from PR#40, to support local preview for Jekyll 3.0
# make sure you have this gem installed
# `$ gem install jekyll-paginate`
plugins: [jekyll-paginate]



# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
kramdown:
  input: GFM                            # use Github Flavored Markdown !important
  syntax_highlighter_opts:
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1


# Disqus settings
disqus_username: shanj


# Google Analytics
ga_track_id: 'UA-138327408-1'            # Format: UA-xxxxxx-xx
ga_domain: shanj.tk

# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true

# MathJax rendering for layout:page (e.g. post preview)
page-mathjax: True
