# Basic
title: Shan's hub
SEOTitle: Shan Jiang, a salarygirl, daughter and life-learner
header-img: img/home-bg.jpg
email: sj2921@caa.columbia.edu
keyword: Previous New Yorker, Blog writter, Novelist
welcome_message: Now I am working on Energy insecuirity and applications of data visulization on social science topics, for more information, <a href="https://shanjiang21.github.io/sociology.html">click here</a>
description: Hi, I am Shan(@shanjiang21), a master student at Columbia University.
url: "https://shanj21.com/"
baseurl: ""

# Publish posts or collection documents with a future date.
future: true

# SNS settings
linkedin_username: shan-jiang-983639153
github_username: shanjiang21
zhihu_username: jiang-shan-59
twitter_username: Alexand43261453

# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
highlighter: rouge
permalink: pretty
paginate: 12
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md","README.zh.md"]
anchorjs: true

# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "Love is a touch <br>and yet not a touch<br>路过人间。"
sidebar-avatar: /img/avatar.jpg

# Featured Tags
featured-tags: true                     # whether or not using Feature-Tags
featured-condition-size: 1.1             # A tag will be featured if the size of it is more than this condition value

# Gems
# from PR#40, to support local preview for Jekyll 3.0
# make sure you have this gem installed
# `$ gem install jekyll-paginate`
plugins:
  - jekyll-paginate
  - jekyll-feed


# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
kramdown:
  input: GFM                            # use Github Flavored Markdown !important
  syntax_highlighter_opts:
    span:
      line_numbers: false
    block:
      line_numbers: false
      start_line: 1


# Disqus settings
disqus_username: shanj


# Google Analytics
ga_track_id: 'UA-138327408-1'            # Format: UA-xxxxxx-xx
ga_domain: shanj21.com


# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true


gallery:
  - url: ../img/3.jpg
    image_path: ../img/3.jpg
    alt: "placeholder image 1"
    title: "Image 1 title caption"
  - url: /img/8.jpg
    image_path: ../img/8.jpg
    alt: "placeholder image 8"
    title: "Image 8 title caption"
  - url: ../img/9.jpg
    image_path: ../img/9.jpg
    alt: "placeholder image 9"
    title: "Image 3 title caption"
